spring.application.name=metrics

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=root